language: php

php:
  - 5.3
  - 5.4
  - 5.5

branches:
  except:
    - gh-pages

services:
  - mongodb
  - rabbitmq

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
  - java -jar selenium-server-standalone-2.35.0.jar -port 4444 &
  - php -S localhost:8000 -t tests/data/app &
  - curl -s http://getcomposer.org/installer | php
  - composer install -n --prefer-source
  - "mysql -e 'create database codeception_test;'"
  - psql -c 'create database codeception_test;' -U postgres

  # Yii2
  - if [$TRAVIS_PHP_VERSION != '5.3']; then composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic frameworks-yii-basic # Yii2
  - if [$TRAVIS_PHP_VERSION != '5.3']; php codecept build -c frameworks-yii-basic # yii2 tests
script:
  - php codecept run # self tests
  - if [$TRAVIS_PHP_VERSION != '5.3']; php codecept run functional -c frameworks-yii-basic # yii2 tests

# Laravel4 Tests

# Symfony2 Tests
