build: false
shallow_clone: true
platform: 'x86'
branches:
  except:
    - gh-pages

cache:
  - vendor -> composer.json

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist -n --no-ansi --dev

test_script:
  - php codecept run cli  --no-ansi -n --skip-group coverage
  - php codecept run unit -g core  --no-ansi -n
  - php codecept run tests/unit/Codeception/Module/FrameworksTest.php --no-ansi -n